/* config.h.  Generated by cmake from config.h.cmake  */

#define MIDORI_VERSION "${PROJECT_VERSION}"
#cmakedefine MIDORI_PLUGIN_PATH "${MIDORI_PLUGIN_PATH}"
#cmakedefine MIDORI_GIT_REVISION "${MIDORI_GIT_REVISION}"

/* Enable portable build */
#cmakedefine PORTABLE_BUILD

/* Disable DBus support */
#cmakedefine DISABLE_DBUS

#cmakedefine01 HAVE_LIBINTL
